kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubeserve
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
	rollingUpdate:
	    maxUnavailable: 1
	    maxSurge: 1
	selector:
      matchLabels:
        app: kubeserve
  template:
      metadata:
        name: kubeserve
        labels: 
          app: kubeserve
  spec:
    containers:
      - name: app
        image: kubeserve: v1		
