apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs
  label:
  type: webserver
spec:
 replicas: 3
 selector:
 matchlabels:
   type: webserver
 template:
   metadata:
    name: mypod
    label:
    type: webserver
   spec:
     containers:
        - name: myc1
          image: nginx
